### ISSUE TITLE
org.gnome.Platform//3.36 is end-of-life

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/de.haeckerfelix.Fragments#7]
org.gnome.Platform//3.36 is end-of-life, which is the runtime version that Fragments uses. Could this be updated to a newer version, say 40 which was released yesterday?

Thanks in advance!

**Comment by haecker-felix** [comment]
Updated with https://github.com/flathub/de.haeckerfelix.Fragments/commit/b2bbb20f4d95df9dcd88df5ffce763e66568fb92
